# Regenerates materials-data.js (base64 of every attachable PDF in materials/).
# Run this after adding or updating a PDF in the materials folder.
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$mats = Join-Path $here 'materials'
$out  = Join-Path $here 'materials-data.js'

# id => filename (user manual intentionally excluded: too large to email)
$map = [ordered]@{
  'brochure'    = 'MiniBox-Plus-Brochure.pdf'
  'why'         = 'Why-MiniBox.pdf'
  'chestsum'    = 'CHEST-2021-Study-Summary.pdf'
  'chestfull'   = 'CHEST-2021-Full-Article.pdf'
  'verona'      = 'Verona-Study.pdf'
  'samplereport'= 'Sample-PFT-Report.pdf'
  'coaching'    = 'PFT-Coaching-Sheet.pdf'
  'comparison'  = 'MiniBox-Competitive-Comparison.pdf'
  'certificate' = 'Manufacturer-Certificate.pdf'
  'hl7'         = 'HL7-Conformance-Statement-2025.pdf'
  'mds2'        = 'MDS2-Cybersecurity-Statement.pdf'
  'financing'   = 'Financing-Quick-Application-2025.pdf'
  'newlane-app' = 'NewLane-Financing-Application-2026.pdf'
  'w9'          = 'PulmOne-W9.pdf'
  'bank'        = 'PulmOne-Bank-Information.pdf'
  'dlco'        = 'DLCO-Gas-Requirements.pdf'
  'achpdf'      = 'ACH-Payment-Authorization.pdf'
  'eolletter'   = 'MiniBox-End-of-Life-Letter.pdf'
  # Rheumatology Playbook files (from Rheum Playbook.zip)
  'rh-slick'     = '01_Rheumatology_Play_Segment_Slick.pdf'
  'rh-fieldref'  = '02_MiniBox_Rheumatology_Field_Reference.docx'
  'rh-deck'      = '03_PFT_Rheumatology_Clinic_Training.pptx'
  'rh-guideline' = '04_ACR_CHEST_ILD_Guideline_2023.pdf'
  'rh-pico'      = '05_ACR_CHEST_PICO_Questions_Appendix.pdf'
  'rh-factsheet' = '06_RA_ILD_Patient_Fact_Sheet_PFF.pdf'
  'rh-emails'    = '07_Email_Templates_Sales_Call_Guide.docx'
  # Specialty one-pagers
  'cardio-onepager' = 'Cardiology-Complete-PFT-Clinical-Billing.pdf'
  'al-getpaid'      = 'Allergy_Will_You_Get_Paid_Reference.pdf'
  # Interactive calculators (self-contained HTML)
  'calc-rheum'      = 'Rheumatology-PFT-Estimator.html'
  'calc-interp'     = 'PFT-Interpretation-Composer.html'
  'calc-pft-coding' = 'How-to-Code-a-PFT.html'
  'calc-roi'        = 'MiniBox-ROI-Calculator.html'
  'calc-proposal'   = 'MiniBox-ROI-Proposal-Builder.html'
  'calc-financing'  = 'MiniBox-Financing-Calculator.html'
  'aging-assess'    = 'MiniBox-Plus-Aging-Device-Assessment.html'
  'calc-filterprice'= 'MiniBox-Filter-Pricing.html'
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/* AUTO-GENERATED by build-materials-data.ps1 - do not edit by hand.')
[void]$sb.AppendLine('   Base64 of each attachable PDF so the toolkit can build real .eml drafts')
[void]$sb.AppendLine('   with genuine attachments, online OR offline. */')
[void]$sb.AppendLine('var MATERIALS_B64 = {};')
foreach ($id in $map.Keys) {
  $f = Join-Path $mats $map[$id]
  if (-not (Test-Path $f)) { Write-Warning "MISSING: $f"; continue }
  $b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($f))
  [void]$sb.AppendLine("MATERIALS_B64['$id'] = '$b64';")
}
[IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Wrote {0} ({1:N1} MB)" -f $out, ((Get-Item $out).Length/1MB))
